# Generated by Django 4.1.2 on 2022-10-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('price', models.IntegerField(null=True)),
                ('brand', models.CharField(max_length=40, null=True)),
                ('stock', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
