# Generated by Django 4.1.2 on 2022-10-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
