# Generated by Django 4.1.2 on 2022-10-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_order_is_active_cart_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_product_cost',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
