# Generated by Django 4.1.2 on 2022-10-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_order_tax_remove_order_total_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_product_cost',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
