# Generated by Django 4.1.2 on 2022-10-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_cart_created_on_cart_updated_on_order_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='total_product_cost',
            field=models.PositiveIntegerField(default=123432),
            preserve_default=False,
        ),
    ]
